### PR TITLE
Added two new logo files with white bg

### PR DESCRIPTION
**Pull request by sakshamsingh01**
Hi! I have added two new logos with white bg as new files as requested. Pardon me for creating a new Pull Request for this, I'm a beginner😅. I am learning.

### CODE REVIEW

**Comment by MrNaif2018** [comment]
No problem! Looking good, but did you create the svg yourself? The font differs. You can just use our logo.svg from this repo and add a white background to it I think

**Comment by sakshamsingh01** [comment]
Sure! I will have a look into it.

**Comment by sakshamsingh01** [comment]
Done! @MrNaif2018 . Everything seems perfect now.

**Review by MrNaif2018 — APPROVED** [review]
Everything looks good now! Thank you very much!

**Pull request merged**
